# Generated by Django 2.2.3 on 2019-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPT_SEC', models.CharField(max_length=15)),
                ('PRESENTATION', models.IntegerField()),
                ('QUERIES', models.IntegerField()),
                ('COMMUNICATION', models.IntegerField()),
                ('AUDIENCE', models.IntegerField()),
                ('TOTAL', models.IntegerField()),
            ],
        ),
    ]
