# Generated by Django 2.2.3 on 2019-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20190730_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='NAME',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
